try:
    from .. import utils
except ImportError:
    import utils


MIN_CANOPY_HEIGHT = 2.0
COVER_THRESHOLD = 0.1
MIN_BIN_POINTS = 2
MIN_COLUMN_POINTS = 5
GAP_TOLERANCE_BINS = 1
MIN_CANOPY_DEPTH_BINS = 2

HEIGHT_BIN_SIZE = 0.5
MIN_PROFILE_HEIGHT = 0.0
MAX_PROFILE_HEIGHT = 60.0

NODATA = utils.DEFAULT_NODATA

HEIGHT_PERCENTILES = (10, 25, 50, 75, 90, 95)
COVER_THRESHOLDS = (0.5, 1.0, 2.0, 5.0)
