# This file handles training and inference of the model. The model used will be random forest.
# Basic structure:
# class CBHModel:
#     def train(self, X, y): ...
#     def predict(self, X): ...
#     def save(self, path): ...
#     def load(self, path): ...
# 
# Uses sci-kit learn where applicable and updates requirements.txt